# Generated by Django 6.0.2 on 2026-02-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=20, verbose_name='Número de serie')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('validez', models.DateField(verbose_name='Fecha de validez')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('impuestos', models.DecimalField(decimal_places=2, default=21, max_digits=5, verbose_name='Impuestos (%)')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', related_query_name='presupuesto', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'permissions': [('puede_convertir_presupuesto', 'Puede convertir presupuesto a factura')],
                'unique_together': {('proyecto', 'numero_serie')},
            },
        ),
    ]
