# Generated by Django 6.0.2 on 2026-02-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', related_query_name='presupuesto', to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
    ]
