# Generated by Django 6.0.2 on 2026-02-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_alter_presupuesto_proyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'permissions': [('puede_convertir_presupuesto', 'Puede convertir presupuesto a factura')], 'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
    ]
