# Generated by Django 6.0.2 on 2026-02-19 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', related_query_name='proyecto', to='clientes.cliente', verbose_name='Cliente')),
                ('freelancer', models.ForeignKey(limit_choices_to={'perfil__tipo_cuenta': 'freelancer'}, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', related_query_name='proyecto', to=settings.AUTH_USER_MODEL, verbose_name='Freelancer')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'unique_together': {('nombre', 'cliente')},
            },
        ),
    ]
