# Generated by Django 6.0.2 on 2026-02-19 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Compañia')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('freelancer', models.ForeignKey(limit_choices_to={'perfil__tipo_cuenta': 'freelancer'}, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', related_query_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Freelancer')),
                ('usuario_cliente', models.OneToOneField(blank=True, limit_choices_to={'perfil__tipo_cuenta': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_cliente', related_query_name='cuenta_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'unique_together': {('freelancer', 'email')},
            },
        ),
    ]
