# Generated by Django 6.0.2 on 2026-02-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=20, verbose_name='Número de serie')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('pagos', models.JSONField(blank=True, default=list, verbose_name='Pagos')),
                ('presupuesto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', related_query_name='factura', to='presupuestos.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'permissions': [('puede_registrar_pago', 'Puede registrar pago'), ('puede_anular_factura', 'Puede anular factura')],
                'unique_together': {('presupuesto', 'numero_serie')},
            },
        ),
    ]
