# Generated by Django 6.0.2 on 2026-02-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'permissions': [('puede_registrar_pago', 'Puede registrar pago'), ('puede_anular_factura', 'Puede anular factura')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
